name: Import Security Reports to DefectDojo

on:
  workflow_call:
    secrets:
      DEFECTDOJO_URL:
        required: true
      DEFECTDOJO_API_KEY:
        required: true
      DEFECTDOJO_ENGAGEMENT_ID:
        required: true

permissions:
  contents: read
  actions: read

jobs:
  defectdojo:
    name: Import des rapports dans DefectDojo
    runs-on: ubuntu-latest

    steps:

      ###############################################################
      # Télécharger tous les artefacts
      ###############################################################

      - name: Télécharger tous les artefacts
        uses: actions/download-artifact@v4
        with:
          path: reports

      ###############################################################
      # Debug
      ###############################################################

      - name: Afficher l'arborescence
        run: |
          echo "===== Rapports téléchargés ====="
          ls -R reports

      ###############################################################
      # Fonction d'import
      ###############################################################

      - name: Importer les rapports
        shell: bash
        env:
          DD_URL: ${{ secrets.DEFECTDOJO_URL }}
          DD_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DD_ENGAGEMENT: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
        run: |

          import_scan () {

            FILE=$1
            TYPE=$2

            if [ ! -f "$FILE" ]; then
              echo "Rapport absent : $FILE"
              return
            fi

            echo ""
            echo "========================================="
            echo "Import de $FILE"
            echo "Type : $TYPE"
            echo "========================================="

            curl --fail \
              -X POST "${DD_URL}/api/v2/reimport-scan/" \
              -H "Authorization: Token ${DD_API_KEY}" \
              -F "engagement=${DD_ENGAGEMENT}" \
              -F "scan_type=${TYPE}" \
              -F "file=@${FILE}" \
              -F "active=true" \
              -F "verified=true" \
              -F "close_old_findings=false" \
              -F "minimum_severity=Info"

          }

          #########################################################

          import_scan "reports/trivy-rapport-complet/trivy-results.json" "Trivy Scan"

          import_scan "reports/trivy-image-rapport/trivy-image-results.json" "Trivy Scan"

          import_scan "reports/zap-rapport/zap_report.json" "ZAP Scan"

          import_scan "reports/sbom-cyclonedx/sbom.json" "CycloneDX"

          import_scan "reports/gitleaks-rapport/gitleaks-report.json" "Gitleaks Scan"

          echo ""
          echo "Tous les imports terminés."