name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write
  actions: write
  packages: write
  id-token: write # requis pour l'auth OIDC GitHub -> Vault (migration progressive des secrets)

jobs:
  security-scans:
    name: Scans de sécurité et tests
    uses: ./.github/workflows/_security-scans.yml
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}

  build-and-scan:
    name: Build et scan de l'image
    needs: [security-scans]
    uses: ./.github/workflows/_build.yml

  deploy:
    name: Déploiement
    needs: [build-and-scan]
    uses: ./.github/workflows/_deploy.yml
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      STAGING_URL: ${{ secrets.STAGING_URL }}

  defectdojo:
    name: Import vers DefectDojo
    # Tourne toujours, même si deploy échoue
    # N'attend PAS le deploy  les scans suffisent
    if: always()
    needs:
      - security-scans
      - build-and-scan
      - deploy
    uses: ./.github/workflows/_defectdojo.yml
    secrets:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}